### ISSUE TITLE
add VC firms who attended to Tech Mission to Israel

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/antipalestinian-vc-funds#14]
https://theintercept.com/2023/12/19/investors-israel-tech-mission-harvard/

**Comment by jeff-dosso** [comment]
I'm assuming the firms are listed in the embeded DocumentCloud?  The iframe points to https://embed.documentcloud.org/documents/24229208-israel-tech-mission-itinerary-2023/?embed=1&title=1  .  Doesn't seem to be a way to download the PDF itslef.

**Comment by pbiggar** [comment]
Actually, I already added these so we could close this issue.
