### ISSUE TITLE
Add a column for source of data

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/antipalestinian-vc-funds#6]
The existing data comes from the og pro-israel list. We need to also add other sources, but we would like to track why someone is on the list. So just add a column saying everyone is from that list, and it will be easier to go from there for adding other sources in PRs.

**Comment by elmodeer** [comment]
I would like to do this.

**Comment by pbiggar** [comment]
Thank you @elmodeer - apologies for lack of comms, I didn't set up my notifications correctly.
